keys:
  - &polarmutex age1vjf2wtuvw6pmjukzkxenw5am3lyuzh74077pzmf4ycsy46vkd4wscr9jth
  - &work age1vfx7yqajaxe2suram0tk7rudv06ra0mrahkvmwpt9t7vcutlf3yqedynz4

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *polarmutex
          - *work
