# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "ohci_pci"
    "ehci_pci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  #boot.kernelPackages = pkgs.linuxPackages;
  #boot.kernelPackages = pkgs.linuxKernel.packageAliases.linux_latest;

  fileSystems."/" =
    {
      device = "rpool/root/nixos";
      fsType = "zfs";
    };
  fileSystems."/home" =
    {
      device = "rpool/home";
      fsType = "zfs";
    };
  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B521-EB4A";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-id/ata-VBOX_HARDDISK_VB2b5a6d0d-7faeb0af-part2";
    }
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  virtualisation.virtualbox.guest.enable = true;
}
