# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zellij = {
    pname = "zellij";
    version = "v0.40.0";
    src = fetchgit {
      url = "https://github.com/zellij-org/zellij.git";
      rev = "v0.40.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-1z7qIgjElE9gw0lY+A17gsYIcnKRceZTFnRd8fMeBg8=";
    };
  };
}
