# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zellij = {
    pname = "zellij";
    version = "v0.40.1";
    src = fetchgit {
      url = "https://github.com/zellij-org/zellij.git";
      rev = "v0.40.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-n8cwsCeKWzTw/psvLL3chBr8EcwGoeKB8JeiLSLna1k=";
    };
  };
}
