# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  drawio = {
    pname = "drawio";
    version = "15.8.7";
    src = fetchurl {
      url = "https://github.com/jgraph/drawio-desktop/releases/download/v15.8.7/drawio-x86_64-15.8.7.rpm";
      sha256 = "sha256-Uy+ZJrSwVcu3Qad41X30LGXFr4LQqIKehzJOteggJeM=";
    };
  };
  logseq = {
    pname = "logseq";
    version = "0.5.4";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.5.4/logseq-linux-x64-0.5.4.AppImage";
      sha256 = "sha256-PGrx2JBYmp5vQ8jLpOfiT1T1+SNeRt0W5oHUjHNKuBE=";
    };
  };
}
