# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build flake

concurrency: build

on:
  pull_request:
  push:
    branches-ignore:
      - 'update/flake'
  workflow_dispatch:

jobs:

  eval:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flake_output: [
          my-zellij
          #nixosConfigurations.polarbear.config.system.build.toplevel,
          #homeConfigurations.'polar@polarbear'.activationPackage
        ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.PAT }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://polarmutex.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= polarmutex.cachix.org-1:kUFH4ftZAlTrKlfFaKfdhKElKnvynBMOg77XRL2pc08=
    - name: Set up cachix
      uses: cachix/cachix-action@master
      with:
        name: polarmutex
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Eval output
      run: nix build .#${{ matrix.flake_output }} -L --dry-run --print-out-paths -j0
