# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Update flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 5"

jobs:
  nvfetcher_matrix:
    name: Generate nvfetcher update matrix
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.matrix.outputs.paths }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v24
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.PAT }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://polarmutex.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= polarmutex.cachix.org-1:kUFH4ftZAlTrKlfFaKfdhKElKnvynBMOg77XRL2pc08=
    - name: Generate matrix
      id: matrix
      run: |
        set -ex
        nix profile install .#jq .#fd
        paths="$(fd 'nvfetcher.toml|sources.toml' | jq -ncR '[inputs]')"
        echo "paths=$paths" >> $GITHUB_OUTPUT

  nvfetcher_update:
    runs-on: ubuntu-latest
    needs: [nvfetcher_matrix]
    if: ${{ needs.nvfetcher_matrix.outputs.paths != '[]' && needs.nvfetcher_matrix.outputs.paths != '' }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.nvfetcher_matrix.outputs.paths )}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v24
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.PAT }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://polarmutex.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= polarmutex.cachix.org-1:kUFH4ftZAlTrKlfFaKfdhKElKnvynBMOg77XRL2pc08=
    - name: Update element
      run: |
        nix run .#nvfetcher -- \
          --build-dir $(dirname ${{ matrix.path }}) \
          --config ${{ matrix.path }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: '${{ secrets.PAT }}'
        title: 'ci: bump ${{ matrix.path }}'
        commit-message: |
          Bump ${{ matrix.path }}


          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: GitHub <noreply@github.com>
        branch: update/${{ matrix.path }}
        delete-branch: true
